# Generated by Django 4.0.4 on 2022-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_date_ordered_alter_invoice_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
